version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: ceneca-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    command: npm run dev 
    
  postgres:
    image: postgres:14-alpine
    container_name: waitlist-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: waitlist_db
    ports:
      - "5460:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: waitlist-backend
    environment:
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=waitlist_db
      - RAZORPAY_KEY_ID=rzp_test_Lpk9B9aflaSSbu
      - RAZORPAY_KEY_SECRET=KaUCdOrSUX70UJunkRr3097i
      - JWT_SECRET=admin-secret-key-change-in-production
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./landing_routes:/app
      - /app/node_modules

volumes:
  pg_data: