version: '3.8'

services:
  ceneca-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: ceneca-agent:latest
    container_name: ceneca-agent
    ports:
      - "8787:8787"
    volumes:
      - ./config.yaml:/root/.data-connector/config.yaml
    environment:
      - AGENT_PORT=8787
      - LLM_API_KEY=${LLM_API_KEY}
    restart: unless-stopped
    networks:
      - ceneca-network
      # Uncomment and modify to join your existing networks
      # - your-postgres-network
      # - your-mongodb-network
      # - your-qdrant-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Optional: Add host mappings if needed for DNS resolution
    # extra_hosts:
    #   - "db-postgres.internal:192.168.1.100"
    #   - "db-mongo.internal:192.168.1.101"
    #   - "db-qdrant.internal:192.168.1.102"

networks:
  ceneca-network:
    driver: bridge
  # Uncomment and modify to reference your existing networks
  # your-postgres-network:
  #   external: true
  # your-mongodb-network:
  #   external: true
  # your-qdrant-network:
  #   external: true 