version: '3.8'

services:
#  api:
#    build: 
#      context: ./server
#      dockerfile: Dockerfile
#    volumes:
#      - ./server:/app
#    ports:
#      - "8000:8000"
#    environment:
#      - ENVIRONMENT=development
#      - DB_HOST=postgres
#      - DB_PORT=5432
#      - DB_NAME=dataconnector
#      - DB_USER=dataconnector
#      - DB_PASS=dataconnector
#    container_name: data-connector-api
#    restart: unless-stopped
#    networks:
#      - connector-network
#    depends_on:
#      - postgres

  postgres:
    image: postgres:16
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_USER=dataconnector
      - POSTGRES_PASSWORD=dataconnector
      - POSTGRES_DB=dataconnector
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    container_name: data-connector-postgres
    networks:
      - connector-network

  mongodb:
    image: mongo:7
    ports:
      - "27000:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dataconnector
      - MONGO_INITDB_ROOT_PASSWORD=dataconnector
      - MONGO_INITDB_DATABASE=dataconnector_mongo
    volumes:
      - mongodb-data:/data/db
      - ./init-mongodb:/docker-entrypoint-initdb.d
    container_name: data-connector-mongodb
    networks:
      - connector-network
    command: ["--auth"]

  qdrant:
    build: ./init-qdrant
    image: qdrant-custom:latest
    ports:
      - "7500:6333"  # HTTP port
      - "7501:6334"  # gRPC port
    volumes:
      - qdrant-data:/qdrant/storage
      - ./init-qdrant:/qdrant/init
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true
    container_name: data-connector-qdrant
    networks:
      - connector-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readiness"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: ["/bin/bash", "-c", "(/qdrant/init/init.sh &) && /qdrant/qdrant"]

networks:
  connector-network:
    driver: bridge

volumes:
  postgres-data:
  mongodb-data:
  qdrant-data: 