sso:
  # Common settings
  enabled: true
  default_protocol: "oidc"
  
  # Azure AD Configuration
  oidc:
    provider: "azure"
    client_id: "{{ AZURE_CLIENT_ID }}"
    client_secret: "{{ AZURE_CLIENT_SECRET }}"
    # Replace {{ AZURE_TENANT_ID }} with your Azure AD tenant ID
    issuer: "https://login.microsoftonline.com/{{ AZURE_TENANT_ID }}/v2.0"
    discovery_url: "https://login.microsoftonline.com/{{ AZURE_TENANT_ID }}/v2.0/.well-known/openid-configuration"
    redirect_uri: "https://{{ YOUR_DOMAIN }}/authorization-code/callback"
    scopes: ["openid", "email", "profile", "Group.Read.All"]
    # Azure AD specific claim mappings
    claims_mapping:
      email: "preferred_username"  # Azure uses preferred_username for email
      name: "name"
      groups: "groups"  # Requires Group.Read.All scope

# Role mappings from Azure AD groups to Ceneca roles
role_mappings:
  # Azure AD group object IDs or display names
  "{{ AZURE_ADMIN_GROUP_ID }}": "admin"  # IT Admins group ID
  "Data Analysts": "analyst"  # Group display name
  "HR Team": "hr_read"
  "Finance Team": "finance_read" 