sso:
  # Common settings
  enabled: true
  default_protocol: "oidc"
  
  # Auth0 Configuration
  oidc:
    provider: "auth0"
    client_id: "{{ AUTH0_CLIENT_ID }}"
    client_secret: "{{ AUTH0_CLIENT_SECRET }}"
    # Replace {{ AUTH0_DOMAIN }} with your Auth0 domain
    issuer: "https://{{ AUTH0_DOMAIN }}.auth0.com/"
    discovery_url: "https://{{ AUTH0_DOMAIN }}.auth0.com/.well-known/openid-configuration"
    redirect_uri: "https://{{ YOUR_DOMAIN }}/authorization-code/callback"
    scopes: ["openid", "email", "profile", "read:current_user"]
    # Auth0 specific claim mappings
    claims_mapping:
      email: "email"
      name: "name"
      groups: "groups"  # Configure in Auth0 Rules/Actions

# Role mappings from Auth0 groups/roles to Ceneca roles
role_mappings:
  # Auth0 role names (configured in Auth0 Dashboard)
  "Data Analyst": "analyst"
  "HR Member": "hr_read"
  "Finance Member": "finance_read"
  "System Admin": "admin" 