version: '3'

[object Object]:

  ceneca:
    image: ceneca/agent:latest
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
      - MONGO_URI=${MONGO_URI}
      - GA4_ID=${GA4_ID}
      - GA4_API_SECRET=${GA4_API_SECRET}
      - LLM_PROVIDER=chatgpt
      - LLM_MODEL=gpt-4.1
      - LOG_LEVEL=info
    [object Object]:
      - ceneca-data:/data

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=ceneca
      - POSTGRES_USER=ceneca
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    [object Object]:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_DATABASE=ceneca
      - MONGO_INITDB_ROOT_USERNAME=ceneca
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    [object Object]:
      - mongo-data:/data/db

[object Object]:
  ceneca-data:
  postgres-data:
  mongo-data:

[object Object]:
  default:
    name: ceneca-network