# Ceneca Configuration
[object Object]:
  postgres:
    host: postgres
    port: 5432
    [object Object]: ceneca
    user: ceneca
    password: changeme
  mongodb:
    host: mongo
    port: 27017
    [object Object]: ceneca
  qdrant:
    host: qdrant
    port: 6333
[object Object]:
  secret_key: changeme
  jwt_expiration: 86400 # 1 day in seconds
[object Object]:
  [object Object]:
    image: ceneca/[object Object]:latest
    replicas: 2
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ceneca
      - POSTGRES_USER=ceneca
      - POSTGRES_PASSWORD=changeme
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=ceneca
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - AUTH_SECRET_KEY=changeme
      - JWT_EXPIRATION=86400
  worker:
    image: ceneca/worker:latest
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ceneca
      - POSTGRES_USER=ceneca
      - POSTGRES_PASSWORD=changeme
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=ceneca
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333