# Ceneca Agent Configuration
# Main configuration for connecting to existing databases

# Default database to use for queries if not specified
default_database: postgres

# PostgreSQL configuration
postgres:
  uri: "postgresql://user:password@your-postgres-host:5432/your_database"
  pool:
    max_connections: 10
    min_connections: 2
  ssl: true  # Enable SSL for secure connections

# MongoDB configuration
mongodb:
  uri: "mongodb://user:password@your-mongodb-host:27017/your_database?authSource=admin"
  pool_size: 10
  connect_timeout_ms: 5000

# Qdrant vector database configuration
qdrant:
  uri: "http://your-qdrant-host:6333"
  api_key: "your-qdrant-api-key-if-needed"  # Optional

# LLM configuration
llm:
  provider: "openai"  # Options: openai, anthropic, local
  model: "gpt-4"      # Model to use
  max_tokens: 2000    # Maximum tokens per request
  temperature: 0.7    # Sampling temperature

# Logging configuration
logging:
  level: "info"       # Options: debug, info, warning, error
  format: "json"      # Options: json, text
  destination: "file" # Options: file, stdout
  file_path: "/var/log/ceneca-agent.log"  # Only used if destination is "file"

# Web interface configuration
web:
  enabled: true
  port: 8787
  host: "0.0.0.0"
  cors:
    enabled: true
    allowed_origins: ["*"]

# Security settings
security:
  request_timeout_seconds: 60
  max_request_size_mb: 10