sso:
  # Common settings
  enabled: true
  default_protocol: "oidc"
  
  # Auth0 Configuration
  oidc:
    provider: "auth0"
    client_id: "your-auth0-client-id"
    client_secret: "your-auth0-client-secret"
    # Replace {domain} with your Auth0 domain
    issuer: "https://{domain}.auth0.com/"
    discovery_url: "https://{domain}.auth0.com/.well-known/openid-configuration"
    redirect_uri: "https://your-ceneca-domain.com/authorization-code/callback"
    scopes: ["openid", "email", "profile", "read:current_user"]
    # Auth0 specific claim mappings
    claims_mapping:
      email: "email"
      name: "name"
      groups: "groups"  # Configure in Auth0 Rules/Actions

# Role mappings from Auth0 groups/roles to Ceneca roles
role_mappings:
  # Auth0 role names (configured in Auth0 Dashboard)
  "Data Analyst": "analyst"
  "HR Member": "hr_read"
  "Finance Member": "finance_read"
  "System Admin": "admin" 