sso:
  # Common settings
  enabled: true
  default_protocol: "oidc"
  
  # Azure AD Configuration
  oidc:
    provider: "azure"
    client_id: "your-azure-application-id"
    client_secret: "your-azure-client-secret"
    # Replace {tenant-id} with your Azure AD tenant ID
    issuer: "https://login.microsoftonline.com/{tenant-id}/v2.0"
    discovery_url: "https://login.microsoftonline.com/{tenant-id}/v2.0/.well-known/openid-configuration"
    redirect_uri: "https://your-ceneca-domain.com/authorization-code/callback"
    scopes: ["openid", "email", "profile", "Group.Read.All"]
    # Azure AD specific claim mappings
    claims_mapping:
      email: "preferred_username"  # Azure uses preferred_username for email
      name: "name"
      groups: "groups"  # Requires Group.Read.All scope

# Role mappings from Azure AD groups to Ceneca roles
role_mappings:
  # Azure AD group object IDs or display names
  "a1b2c3d4-e5f6-7890-abcd-ef1234567890": "admin"  # IT Admins group ID
  "Data Analysts": "analyst"  # Group display name
  "HR Team": "hr_read"
  "Finance Team": "finance_read" 